scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:8080']
  
  - job_name: node_exporter
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9100']
  - job_name: "iperf"
    scrape_interval: 5s
    static_configs:
     - targets: ['localhost:8000']
